# Generated by Django 5.0 on 2025-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='document_image',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
